# Generated by Django 3.2.10 on 2023-08-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sending_type', models.CharField(choices=[('TO_CUSTOMER', 'To Customer'), ('TO_ADMIN', 'To Admin')], help_text='The Email sending type', max_length=200)),
                ('from_email', models.EmailField(help_text='From Email ID', max_length=254)),
                ('subject', models.CharField(blank=True, help_text='Email Subject', max_length=200, null=True)),
                ('message', models.TextField(blank=True, help_text='Email Message/Content', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this email is an Active?')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
