# Generated by Django 3.2.10 on 2023-04-15 10:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=75)),
                ('address_line1', models.CharField(max_length=150)),
                ('address_line2', models.CharField(max_length=150)),
                ('landmark', models.CharField(blank=True, max_length=75, null=True)),
                ('area', models.CharField(max_length=75)),
                ('pincode', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(?!0|1|2|3|4|5)[0-9]{10}$', 'Invalid mobile number!')])),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('coordinate', models.CharField(blank=True, max_length=400, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='home.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='home.state')),
            ],
            options={
                'verbose_name_plural': 'Stores',
            },
        ),
    ]
