# Generated by Django 3.2.10 on 2023-04-19 06:39
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
