version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3030:3030
    networks:
      - react_docker

  browser_sync:
    image: ustwo/browser-sync
    restart: always
    links: 
      - web
    command: start --proxy "web:3030" --files "css/*.css"
    ports:
      - 3001:3001
      - 3000:3000
    networks:
      - react_docker

networks:
    react_docker:
      driver: bridge




