# Generated by Django 3.2.10 on 2023-08-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_selling_product',
            field=models.BooleanField(default=False, help_text='Used to identify best-selling products, (best seller section).'),
        ),
    ]
