# Generated by Django 3.2.10 on 2023-04-18 19:55
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_slot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='booking_type',
            field=models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('SERVICE', 'SERVICE')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
