# Generated by Django 3.2.10 on 2023-04-19 05:36
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('appointment', '0004_bookappointment_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_appointments', to='product.product'),
        ),
    ]
