# Generated by Django 3.2.10 on 2023-04-15 10:51
from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=75)),
                ('answer', django_editorjs_fields.fields.EditorJsJSONField()),
                ('faq_type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('FRANCHISE', 'FRANCHISE')], max_length=10)),
            ],
            options={
                'verbose_name_plural': "FAQ's",
            },
        ),
    ]
