# Generated by Django 3.2.10 on 2023-08-03 11:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django_editorjs_fields.fields
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='The Blog Title', max_length=150)),
                ('title_slug', models.SlugField(help_text='The URL slug', max_length=100)),
                ('meta_title', models.CharField(blank=True, help_text="Blog's Meta Title", max_length=150, null=True)),
                ('meta_description', models.CharField(blank=True, help_text="Blog's Meta Description", max_length=150, null=True)),
                ('short_description', models.CharField(blank=True, help_text="Blog's Short Description", max_length=150, null=True)),
                ('body', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('featured_image_mobile', versatileimagefield.fields.VersatileImageField(help_text='Background image for mobile', upload_to='', verbose_name='Thumbnail Image Mobile')),
                ('featured_image_desktop', versatileimagefield.fields.VersatileImageField(help_text='Background image for desktop', upload_to='', verbose_name='Thumbnail Image Desktop')),
                ('main_image_mobile', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Main image for mobile', null=True, upload_to='', verbose_name='Main Image Mobile')),
                ('main_image_desktop', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Main image for desktop', null=True, upload_to='', verbose_name='Main Image Desktop')),
                ('published_at', models.DateField(auto_now_add=True, help_text='Published Date')),
                ('read_time', models.PositiveIntegerField(default=0, help_text='The Blog read time automatically calculated after save')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(help_text='List the Blogs based on sort order')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Tags for the blog', null=True, size=None)),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('is_featured', 'sort_order')},
            },
        ),
    ]
