# Generated by Django 3.2.10 on 2023-07-19 12:48
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20230419_1305'),
        ('faq', '0002_faqsection_faq_type'),
    ]

    operations = [
    ]
