# Generated by Django 3.2.10 on 2023-08-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_remove_gallerymedia_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymedia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
