# Generated by Django 3.2.10 on 2023-08-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_gallerymedia_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerymedia',
            options={'ordering': ('sort_order',), 'verbose_name_plural': 'Gallery Media'},
        ),
    ]
