# Generated by Django 3.2.10 on 2023-04-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20230417_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymedia',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
