# Generated by Django 3.2.10 on 2023-04-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallerymedia_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymedia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
