# Generated by Django 3.2.10 on 2023-04-18 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallerymedia_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerymedia',
            options={'ordering': ('sort_order',), 'verbose_name_plural': 'Gallery Media'},
        ),
    ]
