# Generated by Django 3.2.10 on 2023-07-20 05:32
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_gallery_type'),
        ('gallery', '0006_alter_gallery_gallery_type'),
    ]

    operations = [
    ]
