# Generated by Django 3.2.10 on 2023-08-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20230801_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymedia',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
