# Generated by Django 3.2.10 on 2023-08-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_gallerymedia_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymedia',
            name='is_active',
        ),
    ]
