# Generated by Django 3.2.10 on 2023-04-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_auto_20230418_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='hosted_url_desktop',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='hosted_url_mobile',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='provider_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='thumbnail_desktop',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='thumbnail_mobile',
        ),
    ]
