# Generated by Django 3.2.10 on 2023-07-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_auto_20230415_1133'),
        ('testimonial', '0007_auto_20230524_1227'),
    ]

    operations = [
    ]
