# Generated by Django 3.2.10 on 2023-04-15 11:23

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='thumbnail_desktop',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='slider/thumbnail_desktop'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='thumbnail_mobile',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='slider/thumbnail_mobile'),
        ),
    ]
