# Generated by Django 3.2.10 on 2023-04-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230415_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
