# Generated by Django 3.2.10 on 2023-04-15 10:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(?!0|1|2|3|4|5)[0-9]{10}$', 'Invalid mobile number!')])),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('01:00 PM', '02:00 PM'), ('02:00 PM', '03:00 PM'), ('03:00 PM', '04:00 PM'), ('04:00 PM', '05:00 PM'), ('05:00 PM', '06:00 PM'), ('06:00 PM', '07:00 PM')], max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_appointments', to='product.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_appointments', to='product.service')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_appointments', to='store.store')),
            ],
            options={
                'verbose_name_plural': 'Book Appointment',
            },
        ),
    ]
