# Generated by Django 3.2.10 on 2023-04-18 18:59
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20230419_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
