# Generated by Django 3.2.10 on 2023-04-15 10:51
import django.core.validators
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('mobile_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='testimonial/mobile_images')),
                ('desktop_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='testimonial/desktop_images')),
                ('hosted_url_mobile', models.FileField(blank=True, null=True, upload_to='testimonial/mobile_video')),
                ('hosted_url_desktop', models.FileField(blank=True, null=True, upload_to='testimonial/desktop_video')),
                ('provider', models.CharField(blank=True, choices=[('YOUTUBE', 'Youtube'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('VIMEO', 'Vimeo')], max_length=40, null=True)),
                ('provider_url', models.URLField(blank=True, null=True)),
                ('thumbnail_mobile', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='', verbose_name='testimonial/thumbnail_mobile')),
                ('thumbnail_desktop', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='', verbose_name='testimonial/thumbnail_desktop')),
                ('role', models.CharField(max_length=30, null=True)),
                ('rating', models.CharField(blank=True, max_length=1, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('testimonial_type', models.CharField(choices=[('CLIENT', 'CLIENT'), ('CELEBRITY', 'CELEBRITY'), ('FRANCHISE', 'FRANCHISE')], max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
