# Generated by Django 3.2.10 on 2023-05-24 06:57

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0006_alter_testimonial_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='desktop_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='testimonial/desktop_images'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='mobile_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='testimonial/mobile_images'),
        ),
    ]
