version: '3'

services:
  nails_backend:
    restart: always
    image: registry.gitlab.com/nails_backend/web-service
    command: gunicorn nails_backend.wsgi:application --bind 0.0.0.0:8009 --workers 3 --log-level=DEBUG
    env_file: .env
    ports:
      - "8009:8009"
    expose:
      - "8000"
    networks:
    - nails_backend_backend_tier

  celery:
    image: registry.gitlab.com/nails_backend/web-service
    command: celery -A nails_backend worker -l info
    env_file: .env
    restart: unless-stopped
    networks:
      - nails_backend_backend_tier

  nginx:
    image: registry.gitlab.com/classmate2/web-service/nginx
    depends_on:
      - nails_backend
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./logs/Nginx:/var/log/nginx/
    networks:
      - nails_backend_backend_tier

volumes:
  static_volume:
    driver: local

networks:
  nails_backend_backend_tier:
    driver: bridge
