# Generated by Django 3.2.10 on 2023-04-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactus_message'),
    ]

    operations = [
       
    ]

