# Generated by Django 3.2.10 on 2023-04-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homeslider_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslider',
            options={'ordering': ('sort_order',), 'verbose_name_plural': 'Home Sliders'},
        ),
    ]
