# Generated by Django 3.2.10 on 2023-07-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230415_1133'),
        ('home', '0005_alter_city_options'),
    ]

    operations = [
    ]
